sudo: required
services:
  - docker

before_install:
  - docker build -t endryha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run endryha/react-test npm test -- --coverage

after_success:
  - docker build -t endryha/multi-client ./client
  - docker build -t endryha/multi-nginx ./nginx
  - docker build -t endryha/multi-server ./server
  - docker build -t endryha/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push endryha/multi-client
  - docker push endryha/multi-nginx
  - docker push endryha/multi-server
  - docker push endryha/multi-worker