sudo: required
services:
  - docker

before_install:
  - docker build -t endryha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run endryha/react-test npm test -- --coverage

after_success:
  - docker build -t endryha/multi-client ./client
  - docker build -t endryha/multi-nginx ./nginx
  - docker build -t endryha/multi-server ./server
  - docker build -t endryha/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push endryha/multi-client
  - docker push endryha/multi-nginx
  - docker push endryha/multi-server
  - docker push endryha/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-638220093828
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY